### ISSUE TITLE
报错：loader TypeError: URL.install is not a function

### ISSUE THREAD

**Issue by fatinghenji** [araea/koishi-plugin-shindan-maker#1]
```
2024-12-01 00:04:58 [I] loader apply plugin shindan-maker:371clg
2024-12-01 00:04:58 [E] loader TypeError: URL.install is not a function
                            at Object.<anonymous> (/root/koishi-app/node_modules/whatwg-url/index.js:8:5)
                            at Module._compile (node:internal/modules/cjs/loader:1546:14)
                            at Object..js (node:internal/modules/cjs/loader:1689:10)
                            at Module.load (node:internal/modules/cjs/loader:1318:32)
                            at Function._load (node:internal/modules/cjs/loader:1128:12)
                            at TracingChannel.traceSync (node:diagnostics_channel:315:14)
                            at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
                            at Module.require (node:internal/modules/cjs/loader:1340:12)
                            at require (node:internal/modules/helpers:141:16)
                            at Object.<anonymous> (/root/koishi-app/node_modules/jsdom/lib/api.js:7:19)
```

**Comment by araea** [comment]
感谢反馈。

才看到，我认为这个报错与本插件的关系不大，从来没遇到过。
